### ISSUE TITLE
Organizers section

### ISSUE THREAD

**Issue by a-y-u-m-i** [JapanSciCom/japanscicom.github.io#2]
Could you add a section that mentions the organizers?

**Comment by neuroamanda** [comment]
@raoofphysics
This is the only real change that needs doing. New section on page for organizers, with tab at top of page just like Schedule, Access, etc. Should be situated after Registration, above footer. 
Just not sure how to co-opt one of the existing sub-pages like we have to make the other sections. Just need a text box, basically, for names and contact info.

**Comment by RaoOfPhysics** [comment]
See this comment for instructions on how to make changes to the team: https://github.com/JapanSciCom/japanscicom.github.io/pull/33#issuecomment-366433010
