### ISSUE TITLE
Add date to Schedule; fix location map info

### ISSUE THREAD

**Issue by neuroamanda** [JapanSciCom/japanscicom.github.io#21]

**Comment by neuroamanda** [comment]
* can URL/map link be added to Access text box?
* extraneous dashes and commas?

cc @raoofphysics

**Comment by RaoOfPhysics** [comment]
@neuroamanda: Can you let me know what exactly you want changed?

**Comment by neuroamanda** [comment]
* add a Google map link; currently there is no obvious way to get to a map, because the map that shows up is not a live link or clickable.
* remove weird extra line and dash in the Access text box
* In Schedule, add "April 20, 2018" to header (<- this is doable, contents of this section has to be changed anyway)
@RaoOfPhysics
