### ISSUE TITLE
add RUC logo, add simultaneous interpretation

### ISSUE THREAD

**Issue by a-y-u-m-i** [JapanSciCom/japanscicom.github.io#34]

**Comment by neuroamanda** [comment]
@a-y-u-m-i Can you provide logo file and JP text to add to schedule and "about" section describing interpretation for morning [this covers all keynotes and flash talks too, right?]?

**Comment by a-y-u-m-i** [comment]
- Will remind RUC to provide logo

- Added JP text about simultaneous interpretation to both sections. I wanted to align the text with the table but couldn't. Could you look into this @neuroamanda? or if you think it's okay as is, we can leave it.

**Comment by a-y-u-m-i** [comment]
@neuroamanda Here's the RUC logo.
![ructf1](https://user-images.githubusercontent.com/35921471/36716575-1da43bc4-1bde-11e8-9e89-00ffbf8d768a.JPG)

**Comment by ejtasker** [comment]
RUC logo added.

**Comment by a-y-u-m-i** [comment]
@ejtasker Thank you!
