### ISSUE TITLE
blue text in Speakers section

### ISSUE THREAD

**Issue by neuroamanda** [JapanSciCom/japanscicom.github.io#36]
change to white against dark background, leave other blue text as-is.

**Comment by ejtasker** [comment]
Changed to white text with a black background... but not convinced I like it! What do you think @neuroamanda @a-y-u-m-i ?

**Comment by neuroamanda** [comment]
@ejtasker Hmm, I'm ok with it as-is (white on black) but I don't mind reverting to blue either.

**Comment by a-y-u-m-i** [comment]
@ejtasker Same here! Both are fine, so please feel free to make changes as you like.

**Comment by ejtasker** [comment]
It's easier to read this way -- let's leave it.
