### ISSUE TITLE
optional: code of conduct text in JP

### ISSUE THREAD

**Issue by neuroamanda** [JapanSciCom/japanscicom.github.io#40]
* translate code of conduct text into Japanese
* in footer: include JP text in link

**Comment by a-y-u-m-i** [comment]
- ELSI may have a Japanese text of the Code of Conduct - will ask Hanako on Wednesday

- Footer: completed

**Comment by neuroamanda** [comment]
@a-y-u-m-i 
Thanks. I tried to find the equivalent text on ELSI's JP site, but nothing...they may not have it in Japanese, because all ELSI events are in English. Anyway, not a big deal, all our participants understand English.
