### ISSUE TITLE
ELSI representation on website (and program)

### ISSUE THREAD

**Issue by ejtasker** [JapanSciCom/japanscicom.github.io#47]
Due to hosting and support, we're considering ELSI as the "Host" above that of basic sponsor. It would be helpful for ELSI to make this clear on the website. Suggested solution: list ELSI as "Host" with a couple of sentences (provided by Hanako) describing how it fits with the ELSI mission. EurekAlert could then be "Sponsor", with also a sentence or two to balance if needed.

**Comment by neuroamanda** [comment]
@ejtasker Are you able to make these changes?

See also  #34 for RUC logo to add (@a-y-u-m-i , link to RUC web? If nothing else, I suggest using this http://www.nins.jp/RUC/ )

Changes for "Sponsors" section: [name of section remains same]

* ELSI listed first, as "Host"
* Below, "With additional support from" with RUC and EurekAlert logos
* Remove current text "Supported by"


Text for "About" section (append as separate last paragraph in English and Japanese sections, respectively. **Note links in text!**

@a-y-u-m-i Please review JP text and adjust host/sponsor meanings as necessary.

---

The Earth-Life Science Institute (ELSI) at the Tokyo Institute of Technology is proud to be a host and supporter of the Japan SciCom Forum 2018. As a World Premier International (WPI) research center (pls make WPI linked to http://www.jsps.go.jp/english/e-toplevel/ <http://www.jsps.go.jp/english/e-toplevel/>) funded by the Japanese government, fostering English-language science communication and outreach in Japan is key to our mission of scientific leadership, globalization, and innovation within the research community. When news of the research carried out in Japan can effectively reach a global audience, the whole national science community will benefit. 

**********

東京工業大学地球生命科学研究所（ELSI）は、ジャパン・サイコム・フォーラム2018を主催しています。当研究所は、国の助成を受けた世界トップレベル研究拠点プログラム（WPI）（※右記へのリンクをお願いします。→ http://www.jsps.go.jp/j-toplevel/) の研究拠点として、日本における英語による科学技術コミュニケーションとアウトリーチを育むことは、科学研究におけるリーダーシップ、グローバリゼーション、研究コミュニティにおけるイノベーションという我々のミッションの鍵となると考えております。日本で行われた研究のニュースが効果的に世界中のオーディエンスに届くことは、日本の科学コミュニティ全体にとって価値のあることです。

**Comment by a-y-u-m-i** [comment]
@neuroamanda @ejtasker I feel that sticking in the JA text in the "About" section doesn't read well. Also, from a participant's point of view, sponsorship information will not be as relevant or informative as the content of the event. Can I suggest that we place the JA&EN texts in the "Sponsors" section, after the ELSI, EA! and RUC listings (in smaller font size)?

Am I allowed to tweak the JA text from Hanako? The JA text is a direct translation of the EN text and I think it needs to be edited a little. I'll suggest the changes to Hanako.

I don't think we need any JA text that are equivalent to "Host" and "With additional support from".

**Comment by a-y-u-m-i** [comment]
Edited version - edits are in bold

東京工業大学地球生命科学研究所（ELSI）は、ジャパン・サイコム・フォーラム2018を主催しています。当研究所は、**文部科学省事業**、世界トップレベル研究拠点プログラム（WPI）（※右記へのリンクをお願いします。→ http://www.jsps.go.jp/j-toplevel/) の研究拠点として、日本における英語による**科学コミュニケーション**とアウトリーチを育むことは、科学研究におけるリーダーシップ、グローバリゼーション、研究コミュニティにおけるイノベーションという**私たち**のミッションを**達成する上で重要である**と考えて**い**ます。日本で行われた研究のニュースが世界中の**人々に知れ渡ることは**、日本の科学コミュニティ全体にとって**有益となることでしょう**。

**Comment by ejtasker** [comment]
Done! Text is easily editable in the _config file (I used Ayumi's Japanese: I trust her!)

(Messed around with the css file as well at partners.html and partners.yml, so these will come through as changes when you next 'fetch').
