### ISSUE TITLE
Re: registraton/live/video text update

### ISSUE THREAD

**Issue by neuroamanda** [JapanSciCom/japanscicom.github.io#50]
**Delete -->** Registration is now full. Walk-in attendance may be possible on the day but is not guaranteed. Tune into the livestream starting at 9:00 on April 20. *Update* Recordings of the morning session can now be viewed.

**Replace with -->** Video from the morning sessions is now online
(corresponding JP text also)

Leave as-is: Registration button and link

Remove: 2nd button ("Recording")
(or change text to say *NEW* VIDEO)

@a-y-u-m-i

**Comment by a-y-u-m-i** [comment]
@neuroamanda Done!

Couldn't figure out how to remove blue button so I changed the wordings as suggested. Please remove blue button when you can, if you know how to. Thanks.
