### ISSUE TITLE
JP text edits

### ISSUE THREAD

**Issue by neuroamanda** [JapanSciCom/japanscicom.github.io#8]
Let us know: Line breaks, mention of interpretation in morning (if confirmed & paid by RUC?), relevance to Japanese speakers regardless of work language. etc. @a-y-u-m-i 
* Add RUC as sponsor?

**Comment by a-y-u-m-i** [comment]
@neuroamanda @ejtasker 
Please find below the Japanese text for the Schedule section.

9:00 - 10:00 | Keynote presentations / 基調講演（3件）
10:00 - 10:30 | Coffee and interaction time / コーヒーブレイク
10:30 - 11:00 | Panel discussion and speaker Q & A / パネル討論（基調講演の講演者との質疑応答含む）
11:00 - 12:00 | Flash talks: hear from institutions around Japan / 国内の機関より5分間プレゼン
12:00 - 14:00 | Lunch: please explore one of the local restaurants in the Ookayama area / 昼食（各自）
14:00 - 15:30 | Workshop: hands-on experience at different SciCom activities / ワークショップ１
15:30 - 16:00 | Coffee and interaction time / コーヒーブレイク
16:00 - 17:30 | Workshop: try a different SciCom activity / ワークショップ２
17:30 | Wrap-up / まとめ
17:45 | Reception / 懇親会

**Comment by a-y-u-m-i** [comment]
@neuroamanda @ejtasker

Here are the line breaks and spaces to make the Japanese easier to read. I don't know how much you are familiar with Japanese writing styles, but text-book style writing suggests that we insert a space at the very beginning of each paragraph.

I've also changed the wording a little to add the  "relevance to Japanese speakers regardless of work language" flavor.

　英語による科学広報やアウトリーチといった、科学を伝える活動は、今、日本で活気を帯びています。本イベントは、サイエンスコミュニケーター、サイエンスライター、研究者、ジャーナリストやこの分野の選りすぐりの海外の専門家が一堂に会する場を提供しようとする初めての試みです。海外に向けた研究成果の情報発信に携わる人をはじめ、科学広報やアウトリーチに興味や関心のあるすべての方が参加いただけるイベントです。

　午前中の基調講演とパネルディスカッションでは、科学や研究成果を題材とした広報や情報発信に特有の課題について、国内にとどまらず、海外の事例を含めて検討します。午後には、複数のグループに別れて、参加者が実際に手を動かして、国外向けの科学広報やアウトリーチの業務に活かせるような実践的なワークショップを行います。本イベントの使用言語は英語です。

　ジャパン・サイコム・フォーラム2018で、英語による科学広報やアウトリーチのスキルを磨き、横のつながりを作り、互いのベストプラクティスを情報交換しませんか。

**Comment by a-y-u-m-i** [comment]
@neuroamanda @ejtasker 

Please add the following Japanese text to the Contact section.
It's a line that says, inquiries can be sent in Japanese.

Contact / お問い合わせ
* 日本語でのお問い合わせにも対応しています
Email
